# Generated by Django 2.2.11 on 2020-04-09 23:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('sound', models.FileField(upload_to='sounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
            ],
            options={
                'ordering': ('text',),
            },
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_datetime',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_correct', models.BooleanField()),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_cards.Card')),
                ('learning_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='apps_cards.LearningSession')),
            ],
        ),
    ]
