# Generated by Django 2.2.11 on 2020-04-07 03:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_cards', '0003_learningsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningsession',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps_cards.Card')),
                ('learning_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_cards.LearningSession')),
            ],
        ),
    ]
