# Generated by Django 2.2.11 on 2020-04-07 04:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_cards', '0004_auto_20200407_0308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningsession',
            options={'ordering': ('-start_datetime',)},
        ),
        migrations.AddField(
            model_name='answer',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='answer',
            name='learning_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='apps_cards.LearningSession'),
        ),
    ]
