# Generated by Django 2.2.11 on 2020-04-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_cards', '0005_auto_20200407_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='sound',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
