# Generated by Django 2.2.11 on 2020-04-08 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_cards', '0006_card_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sound',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
