# Generated by Django 2.2.11 on 2020-04-09 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_cards', '0007_auto_20200408_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sound',
            field=models.FileField(upload_to='sounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
